### PR TITLE
Add Option to Bind to Address

### PR DESCRIPTION
**Pull request by jxmx**
This patchset adds a BindAddress configuration option to allow binding of YSFReflector to one particular IP on a host.

### CODE REVIEW

**Comment by g4klx** [comment]
Please change your code so that you pass a std::string by reference rather than a char* as an argument.

**Comment by jxmx** [comment]
OK

**Comment by jxmx** [comment]
Okay, I think that should be better. Should have done that the first time.

**Comment by jxmx** [comment]
Thanks! You code and work are terrific and I'm very grateful for it. - N8EI

**Pull request merged**
