### PR TITLE
Update FCSNetwork.cpp

### PR DESCRIPTION
**Pull request by dg9ffm**
use m_address to resolve FCSxxx.xreflector.net. all servers have the same domain name.

### CODE REVIEW

**Comment by g4klx** [comment]
I don't like these two pull requests (why two?), it does not allow for the possibility of an independent server at a later date.

Do you know anything about the IMRS protocol?

**Comment by dg9ffm** [comment]
> 
> 
> I don't like these two pull requests (why two?), it does not allow for the possibility of an independent server at a later date.
> 
> Do you know anything about the IMRS protocol?

At the moment there doesn't seem to be any other fcs reflectors than those from xreflector.net

At this point in time it seems like the cleanest solution.

**Comment by oe1kbc** [comment]
> I don't like these two pull requests (why two?), it does not allow for the possibility of an independent server at a later date.
> 
> Do you know anything about the IMRS protocol?

We have included IMRS by self reengineering to our YCS-Server. I do not own any original document. Sorry

**Comment by oe1kbc** [comment]
As Peter wrote, FCSxxx in the moment all running on fcsxxx.xreflector.net. Jonathan do you think we can combine a coded address-table with dynamic fcs url building? it would be three more coding lines

**Comment by g4klx** [comment]
I didn’t expect an original document, just sharing what information you have on IMRS so I can implement it in the MMDVM.


Sent from Yahoo Mail for iPhone


On Friday, September 4, 2020, 11:25, Kurt <notifications@github.com> wrote:





I don't like these two pull requests (why two?), it does not allow for the possibility of an independent server at a later date.

Do you know anything about the IMRS protocol?


We have included IMRS by self reengineering to our YCS-Server. I do not own any original document. Sorry

**Pull request closed without merging**
