### PR TITLE
Update YSFHosts.txt

### PR DESCRIPTION
**Pull request by vk4tux**
Please leave removed as per previous pull.

### CODE REVIEW

**Comment by dg9vh** [comment]
@vk4tux this remove was ok and coordinated with the registrant of the reflector. He registeted his hotspot by misunderstanding the system itself. So there would never been a YSFReflector planned to be setup.

Therefore deletion of this entry made sense.

**Comment by dg9vh** [comment]
I see you removed yourself, I thought this was my removeing of yesterday.

Sorry for misunderstanding.

I would remove you also from the registry database.

73
Kim

**Comment by vk4tux** [comment]
Yes YSF001 is not part of your 'system'

**Comment by dg9vh** [comment]
No problem, you wished would be respected immediately. Your YSF001 is no more part of the YSFRegistry-Database and therefore as you pulled no more part of this YSFHosts.txt

**Pull request merged**
