### PR TITLE
No log

### PR DESCRIPTION
**Pull request by phl0**
Added a command line parameter that allows for completely resign writing a logfile.
Tested by @ernix66

### CODE REVIEW

**Comment by g4klx** [comment]
This would be a useful feature for all of the programs in this suite!

**Comment by phl0** [comment]
Already working on that. Also spreading that to P25Clients.

**Comment by phl0** [comment]
cli parameter or config entry for gateway and reflector?

**Comment by g4klx** [comment]
I think the command line if fine. I'm concerned about how the logging works with the log file not open. It might do the right thing, but not for the right reason.

**Comment by phl0** [comment]
I had a look at YSFGateway and YSFReflector. Setting FileLevel to 0 in the configs prevents logging to a file. So this function is implemented already (with the difference that it is deactivated using config rather than a cli parameter). So I think we can take this PR as it is implementing the nolog feature with cli parameter for YSFParrot. I will make a second PR for P25Parrot.

**Pull request merged**
